name: terraform_validation

on:
  push:
    branches:
      - main

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: terraform_initialize
        run: terraform init
      - name: terraform_validate
        run: terraform validate
      - name: terraform_plan
        run: terraform plan
  
