name: terraform_validation

on:
  push:
    branches:
      - main

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: terraform_initialize 
        run: terraform init
        
      - name: terraform_validate
        run: terraform validate
        
      - name: terraform_plan
        run: terraform plan
  
